apiVersion: v1
kind: Service
metadata:
  name: a2eg-backend-svc
spec:
  selector:
    app: a2eg-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a2eg-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "a2eg-static-ip"
    networking.gke.io/managed-certificates: "a2eg-cert"
spec:
  rules:
    - http:
        paths:
          - path: /api/*
            pathType: Prefix
            backend:
              service:
                name: a2eg-backend-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: a2eg-frontend-svc
                port:
                  number: 80
